# Shifter API Tests
@hostname = https://localhost:7176

###

### Register a New User
# 1. Register
POST {{hostname}}/api/auth/register
content-type: application/json
{
  "email": "registerTest@example.com",
  "password": "SuperSecure1!",
  "confirmPassword": "SuperSecure1!",
  "firstName": "Test",
  "lastName": "User",
  "companyName": "Test Company",
  "companyAbn": 123456789
}

###

# 2. Verify Email
@userId = PASTE_USER_ID_HERE
@token = PASS_THE_TOKEN_FROM_EMAIL

GET {{hostname}}/api/auth/verify-email?userId={{userId}}&token={{token}}

### Login and MFA Verification

# 1. Login
POST {{hostname}}/api/auth/login
Content-Type: application/json

{
  "email": "registerTest@example.com",
  "password": "SuperSecure1!"
}

###

# 2. MFA Verification
# Replace 'PASTE_YOUR_MFA_TOKEN_HERE' with the 'mfaToken' value from the Login response
POST {{hostname}}/api/auth/verify-mfa
Content-Type: application/json
Authorization: Bearer PASTE_YOUR_MFA_TOKEN_HERE

{
  "code": "123456"
}